_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # For better, more stable performance initialize from COCO
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: False
  RESNETS:
      DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 8
# This is similar to the setting used in Mask R-CNN paper, Appendix A
# But there are some differences, e.g., we did not initialize the output
# layer using the corresponding classes from COCO
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
OUTPUT_DIR: "./resnet_24000_city_foggy_2/"
DATASETS:
  TRAIN: ("foggy_cityscapes_train",)
  TEST: ("foggy_cityscapes_val",)
# first time
# SOLVER:
#   BASE_LR: 0.001
#   STEPS: (400,)
#   MAX_ITER: 500
#   IMS_PER_BATCH: 1
# TEST:
#   EVAL_PERIOD: 250

# second time
SOLVER:
  BASE_LR: 0.0005
  STEPS: (600,)
  MAX_ITER: 800
  IMS_PER_BATCH: 1
TEST:
  EVAL_PERIOD: 800